package ayzekssoft.nextday.dto;

public enum Category {
    CLOTHING_TSHIRT,
    CLOTHING_SWEATSHIRT,
    CLOTHING_JEANS,
    CLOTHING_SHOES,
    CLOTHING_JACKET,
    HOME_TSHIRT,
    HOME_UNDERWEAR,
    HOME_PANTS,
    BACKPACK_ITEM,
    WATCH_STRAP,
    WATCH_FACE,
    WALLPAPER_IPHONE,
    WALLPAPER_MACBOOK,
    WALLPAPER_IPAD,
    UNDERWEAR_PANTIES,
    UNDERWEAR_SOCKS,
    UNDERSHIRT,
    COSMETIC_SHAMPOO,
    COSMETIC_GEL,
    COSMETIC_DEODORANT,
    COSMETIC_SPRAY,
    COSMETIC_ANTIPERSPIRANT,
    COSMETIC_CREAM,
    COSMETIC_HAIR_SPRAY
}


